### ISSUE TITLE
[Device request FEATURE] The form of device request need to have these fields  " Current office", "Devices", "Reason"

### ISSUE THREAD

**Issue by kimyen2k** [nccasia/w2-ui#104]
**Expected Result**

The form of device request need to have these fields 
" Current office", "Devices", "Reason"

**Comment by kimyen2k** [comment]
discuss about changing the field name: Content -> Reason

**Comment by tindoancong** [comment]
I changed Content -> Reason

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/235035055-0d3dad18-8596-40eb-90de-d4cfb480bc46.png)
