### ISSUE TITLE
"Select a Type" title is blurred when selecting any option in New Task popup

### ISSUE THREAD

**Issue by kimyen2k** [nccasia/w2-ui#115]
### Pre-condition
Login W2 successfully 

### Steps to reproduce the problem

1. Move to My Task in the sidebar
2. Click New Task button to open pop-up
3. Click any option
4. Observe the title "Select a Type"

### Expected Result
 1. The title "Select a Type" is always clear
 
### Actual Result
 "Select a Type" title is blurred when selecting any option in New Task popup

### Screenshots
![image](https://user-images.githubusercontent.com/130328205/235077636-90116c95-5332-43c5-a4ea-5e1a34204528.png)

**Comment by tindoancong** [comment]
I removed this function because it is not needed anymore

**Comment by kimyen2k** [comment]
Retest
Removed this New Task button on the page of My tasks

![Image](https://github.com/nccasia/w2-ui/assets/130328205/9b0bde95-bf3d-42e0-a4a3-3f07ae6a76c8)
