### ISSUE TITLE
Sign in screen > Can't Sign in by enter account manually

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#44]
### Steps to reproduce the problem

1. Go to the W2 page
2. Input correct email
3. Input correct password
4. Click on Sign-in button
5. Observe

### Expected Result

User should sign-in successfully with correct credential and the W2 homepage will be shown after that

### Actual Result

Sign-in unsuccessfully and show error msg as below

### Screenshots
![alt](https://i.imgur.com/xJN4Mpx.jpg)

**Comment by tindoancong** [comment]
pending
