### ISSUE TITLE
Sidebar > The "Change Office Request" option isn't fully displayed

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#45]
### Steps to reproduce the problem

1. Login to the portal
2. Observe the side bar

### Expected Result

The "Change Office Request" should be displayed fully on the sidebar as the other options

### Actual Result
The "Change Office Request" option isn't fully displayed

### Screenshots
![alt](https://i.imgur.com/PPCfFZo.png)

**Comment by vuidv54** [comment]
fixed

**Comment by trucnguyen31** [comment]
done
![image](https://user-images.githubusercontent.com/127380920/230287390-0dedf8b4-8e61-44c7-b6dc-d85101149602.png)
