### ISSUE TITLE
Sidebar > Spelling mistake: Inconsistency between "Device Requests" and others

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#46]
### Steps to reproduce the problem

1. Login to the portal
2. Observe the "Device Requests" option at the sidebar

### Expected Result

The last letter "s" of "Device Requests" should be removed

### Actual Result

Inconsistency between "Device Requests" and others

### Screenshots
![alt](https://i.imgur.com/1JzI2Ay.png)

**Comment by vuidv54** [comment]
fixed

**Comment by kimyen2k** [comment]
**Retest
Status**: Done
**Screenshot**
![image](https://user-images.githubusercontent.com/130328205/230823480-a16012c2-cec4-47f4-bfb5-8bfbc4f84b62.png)
