### ISSUE TITLE
WFH Request > WFH Request page displays with the Devices requests

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#51]
### Pre-Condition

- User logins successfully and is on the homepage
- There're has been at least 1 device request created successfully

### Steps to reproduce the problem

1. Click on the WFH request at the sidebar
2. Observe the type of existing tasks on the page

### Expected Result

There should be WFH requests displaying only

### Actual Result

The WFH request page displays with the Device requests

### Screenshots

![alt](https://i.imgur.com/700om4c.png)

**Comment by kimyen2k** [comment]
New Bug related to this section **(Wait for Dev fix this issue in another ticket)**
1. Can not submit WFH request even though user has fulfilled all required fields. 


![Image](https://user-images.githubusercontent.com/130328205/232370713-add4be14-57aa-433e-8e56-597acb0085f7.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/233896218-02b01d52-645b-4598-b095-77dfd2959736.png)
