### ISSUE TITLE
WFH Request > WFH request popup > Lack of error msg of Start Date & End Date inputted fields

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#53]
### Pre-condition
User logins successfully an is on the W2 homepage

### Steps to reproduce the problem

1. Click on "WFH Request"  at the sidebar
2. Click on the "New task" button on the Tasks page
3. Let all inputted fields empty
4. Click on "Submit" button
5. Observe

### Expected Result

Error msg for Start Date & End Date inputted fields should be also displayed 

### Actual Result
- Lack of error msg of Start Date & End Date inputted fields
- Just the error msg of Content textbox displays only

### Screenshots
![alt](https://i.imgur.com/MMdI1gr.png)

**Comment by kimyen2k** [comment]
1. Error messages should display under each field 
2. The first letter of every error message should be capitalized

![Image](https://user-images.githubusercontent.com/130328205/232365882-b4026fc7-c7b0-4572-ae8c-32480abadad1.png)

**Comment by kimyen2k** [comment]
Done

![Image](https://user-images.githubusercontent.com/130328205/235050758-ab96fdea-0b18-460b-999d-fc0a7b629cc2.png)
