### ISSUE TITLE
WFH Request > Unable to submit the WFH request

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#58]
### Pre-Condition

User logins successfully and is on the W2 homepage

### Steps to reproduce the problem

1. Click on "WFH Request"  option at the sidebar
2. Click on "New task" button to create a request
3. Input all required information on WFH request popup
4. Click on "Submit" button
5. Observe

### Expected Result

The request should be submitted successfully

### Actual Result

Unable to submit the WFH request

### Screenshots
Please take a look on below video
https://drive.google.com/file/d/1GQHX-dg6ax0KDsui4Fjw2AuiIkChf3QX/view?usp=share_link

![alt](https://i.imgur.com/HL3Hzji.png)

**Comment by kimyen2k** [comment]
done 


![Image](https://user-images.githubusercontent.com/130328205/233896911-365808ef-8c41-4b84-8514-69f7774fddaf.png)
