### ISSUE TITLE
WFH request > The filter option doesn't work

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#61]
### Pre-Condition

- User login successfully and is on the W2 homepage
- There're available task requested before

### Steps to reproduce the problem

1. Click on "WFH Request" option at the sidebar
2. Click on "Setting" icon that is next to the "New task" button
3. Click on slider button at any option to filter the task

### Expected Result

All the tasks should be displayed according to the applied filter option

### Actual Result

The filter options don't works

**Comment by trucnguyen31** [comment]
Note: this issue happens on Change office & Device Request task page too

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/236106630-e1506263-cfc2-4aa0-a01f-0f51f7b34a5c.png)
