### ISSUE TITLE
Change Office > Can submit the request with the inputted current office only

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#62]
### Pre-Condition

User login successfully and is in W2 homepage

### Steps to reproduce the problem

1. Click on "Change Office Request"  at the sidebar
2. Click on "New task" button
3. Select an option at Current Office field
4. Let the other fields empty
5. Click on "Submit" button
6. Observe

### Expected Result

- User shouldn't be able to submit the request
- Error msg should displayed to indicate the missing required fields

### Actual Result

Can submit the request with the inputted current office only

### Screenshots
Please refer this video: https://drive.google.com/file/d/1WxertuVaj5q-eP2Y24_tpD77H5uh5kBY/view?usp=share_link
![alt](https://i.imgur.com/Wh5btoE.png)

**Comment by kimyen2k** [comment]
1. Error messages should display under each field
2. The first letter of every error message should be capitalized


![Image](https://user-images.githubusercontent.com/130328205/232366988-bedf7509-3cb3-48bd-a397-880bcf0b4c2f.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/235051776-1d56a3b2-3fe7-4b58-8d7f-46346fe763c2.png)
