### ISSUE TITLE
Change Office > Can submit the request with the same current and new office location

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#63]
### Pre-Condition

User login successfully and is in W2 homepage

### Steps to reproduce the problem

1. Click on "Change Office Request" option at the sidebar
2. Click on "New task" button
3. Select an option at Current Office field
4. Select the same option at Destination Office
5. Select a date                                             
7. Click on "Submit" button
8. Observe

### Expected Result

- User shouldn't be able to submit the request
- Error msg should displayed to indicate the duplicated office

### Actual Result

Can submit the request with the inputted current office only

### Screenshots
Please refer this video: https://drive.google.com/file/d/1emtOGhMiSPz2c-OlDBa4fdnCVXCU2YiY/view?usp=share_link
![alt](https://i.imgur.com/VYfXOVe.png)

**Comment by kimyen2k** [comment]
Done

![Image](https://user-images.githubusercontent.com/130328205/235052002-a0e8946f-a71a-4dd5-a89c-39052c7f2b66.png)
