### ISSUE TITLE
Device Request > Can submit the request successfully without filling the form

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#65]
### Pre-Condition

User logins successfully and is on the W2 homepage

### Steps to reproduce the problem

1. Click on the Device Request option at the sidebar
2. Click on "New Task" button
3. Not input anything
4. Click on  "Submit" button
5. Observe

### Expected Result

There should be error msg warning user to complete the required fields

### Actual Result

Can submit the request successfully without filling in the form

### Screenshots
Please refer video below
https://drive.google.com/file/d/1sqGG3qvVqzqe72DZSLIdBBLdXsYJQPTA/view?usp=share_link

![alt](https://i.imgur.com/R89rqAz.png)

**Comment by kimyen2k** [comment]
1. Error messages should display under each field
2. The first letter of every error message should be capitalized



![Image](https://user-images.githubusercontent.com/130328205/232369413-2ef6051a-954d-4d08-a7ab-d35e774fdeee.png)

**Comment by kimyen2k** [comment]
Done 



![Image](https://user-images.githubusercontent.com/130328205/235115981-32cecad8-7850-466a-8957-ed624e7a0d1e.png)
