### ISSUE TITLE
Device Request > PM/IT role > Can accept the request successfully without inputted reason

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#67]
### Pre-Condition

- User login successfully to W2 by using PM/IT account 
- There's at least 1 device request sent to PM/IT email

### Steps to reproduce the problem

1. Go to the email inbox
2. Click on the received Device Request email
3. Click on "View Task Detail" at the bottom of that mail (User will be directed to that request page on W2)
4. Click on Approve option
5. Not fill in the Reason inputted field
6. Click on "Submit" button
7. Observe

### Expected Result

- Reason textbox should be highlighted in red 
- There's should be an error msg indicated to show user have to input reason before approve the request

### Actual Result

- Can accept the request successfully without inputted reason
- Successful popup is displayed

### Screenshots
Please refer video below
https://drive.google.com/file/d/1emtOGhMiSPz2c-OlDBa4fdnCVXCU2YiY/view?usp=share_link

![alt](https://i.imgur.com/ugPGcBG.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/233898009-cef6a95e-ac27-4296-8e2d-7a2e5bb4f88e.png)



![Image](https://user-images.githubusercontent.com/130328205/233898014-0f0e6208-f12f-4e50-8f54-4ce0fd66e342.png)
