### ISSUE TITLE
Device Request Approval> PM/IT role > The Submit button is a bit close to the textbox

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#69]
### Pre-condition

- User login successfully to W2 by using PM/IT account
- There's at least 1 device request sent to PM/IT email

### Steps to reproduce the problem

1. Go to the email inbox
2. Click on the received Device Request email
3. Click on "View Task Detail" at the bottom of that mail (User will be directed to that request page on W2)
4. Observe

### Expected Result

The distance from reason textbox to the Submit button should be a bit wider

### Actual Result

The Submit button is a bit close to the textbox

### Screenshots
![alt](https://i.imgur.com/8KBfyFH.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/232652214-f156f015-69a9-486f-a7f8-8267d2241d16.png)



![Image](https://user-images.githubusercontent.com/130328205/232652218-7511940f-932f-488c-9f51-71b84ae4a256.png)
