### ISSUE TITLE
Device Request Approval> PM/IT role > Subtasks > Assignee label is too close to the name

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#70]
### Pre-Condition

- User login successfully to W2 by using PM/IT account
- There's at least 1 device request sent to PM/IT email

### Steps to reproduce the problem

1. Go to the email inbox
2. Click on the received Device Request email
3. Click on "View Task Detail" at the bottom of that mail (User will be directed to that request page on W2)
4. Click on any subtask
5. Observe the Assignee dropdown field

### Expected Result

The distance from Assignee label to the name should be a bit wider or the Assignee label should be outside of the dropdown field

### Actual Result

Assignee label is too close to the name

### Screenshots
![alt](https://i.imgur.com/A836QRp.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/231684218-11567631-ed99-4257-a0c0-a2ac41a77780.png)
