### ISSUE TITLE
Device request > Task Comment > The error msg isn't suitable

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#72]
### Pre-condition

- User logins successfully and is in the W2 homepage
- There's at least 1 device request created before

### Steps to reproduce the problem

1. Click on "Device Request" option at the sidebar
2. Click on a specific task to view its details
3. Scroll to the bottom of the the detail page to the Comment section
4. Not input anything at comment textbox
5. Click on Send button
6. Observe the error msg

### Expected Result

The error msg should be changed to "Please enter the content to comment" 

### Actual Result

The error msg isn't suitable

### Screenshots
![alt](https://i.imgur.com/95yFPgn.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/231637221-bc331352-8ef0-4324-ba3d-e4c84d2c1b4e.png)
