### ISSUE TITLE
Device Request popup > The first line of device inputted fields isn't displayed

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#74]
### Pre-Condition

User logins successfully and is on the W2 homepage

### Steps to reproduce the problem

1. Click on "Device Request" option at the sidebar
2. Click on the "New Task" button 
3. Observe the Device Request popup

### Expected Result

The first line of device inputted fields should be displayed instead of the Add button

### Actual Result

The first line of device inputted fields isn't displayed

### Screenshots
ER:
![alt](https://i.imgur.com/RQktvyl.png)
AR:
![alt](https://i.imgur.com/sK99M6n.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/232370161-b5ca69fa-9b35-4b3f-9639-a0ba6d8fccbf.png)
