### ISSUE TITLE
Device Request > Task Comment > The distance between user's logo to the name is a bit wide

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#78]
### Pre-Condition

- User logins successfully and is on W2 homepage
- There's at least 1 request created before

### Steps to reproduce the problem

1. Click on "Device Request" option at the sidebar
2. Click on a specific task to view its details
3. Scroll to the bottom of the the detail page to the Comment section
4. Input the content into comment textbox
5. Click on Send button
6. Observe 

### Expected Result

The user's logo and name should be closer

### Actual Result

The distance between user's logo to the name is a bit wide

### Screenshots
![image](https://user-images.githubusercontent.com/127380920/230294653-73089045-3e55-4c80-bfb7-2f0039d8c81e.png)

**Comment by kimyen2k** [comment]
After the distance between user's logo and name was fixed, there are 3 new bugs. They happen in all tasks, not only Device Request

1. The first letter of the name is blurred 

![Image](https://user-images.githubusercontent.com/130328205/231678506-3d3c2487-77a1-4c64-b5ba-6611cf9aa6e6.png)

EXPECTED RESULT: all the letters of the name are clear

2. When hovering the logo, the name is partially covered


![Image](https://user-images.githubusercontent.com/130328205/231678116-6213c6f0-82c6-44d4-b58b-fe9f16d501df.png)

EXPECTED RESULT: the name is not covered when hovering the logo

3. should adjust the layout of the time to look better 

![Image](https://user-images.githubusercontent.com/130328205/231692441-eb6f33db-4a57-4f3e-944b-06fc2228d7cf.png)

**Comment by kimyen2k** [comment]
Retest
Done 



![Image](https://user-images.githubusercontent.com/130328205/231940160-039fb06a-fc14-40c0-8f2c-cda04eabc81a.png)
