### ISSUE TITLE
Received Email > Spelling mistake in "Please follow the request and report to admin incase something when wrong." sentence

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#80]
### Pre-condition

- User has sent a request successfully
- The email announcing the request has been sent to user already

### Steps to reproduce the problem

1. Navigate to mail inbox
2. Click on the above mail 
3. Observe 

### Expected Result

"when" should be changed to "went"  
The whole sentence should be: Please follow the request and report to admin incase something went wrong

### Actual Result

Spelling mistake in "Please follow the request and report to admin incase something when wrong." sentence

### Screenshots
![image](https://user-images.githubusercontent.com/127380920/230874693-48ac9bc2-dbbb-4caa-89d6-625dc2222d32.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/233898755-0e285aa3-b883-4ace-93d2-3ac1f38e5b4f.png)
