### ISSUE TITLE
Responsive > Mobile mode > Broken layout of Task details page

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#81]
### Pre-condition

- User login successfully and is on the W2 homepage
- User is on mobile mode
- There's at least 1 request created before

### Steps to reproduce the problem

1. Click on any option at the sidebar
2. Click on a specific request
3. Observe

### Expected Result

All components should be fit to the mobile mode

### Actual Result

Broken layout of Task details page

### Screenshots

![2023-04-10_16h44_27](https://user-images.githubusercontent.com/127380920/230878840-97f00c8d-f933-423f-a934-d4fbdbaeba11.png)
![2023-04-10_16h44_36](https://user-images.githubusercontent.com/127380920/230878858-42a8c6e3-bee7-4fe6-b4b8-561e9eeceddd.png)

**Comment by kimyen2k** [comment]
Sub Tasks section is still quite messy 


![Image](https://user-images.githubusercontent.com/130328205/233900129-83c6bf1c-b5cd-4772-a9c1-21b3ef6eb0c6.png)

**Comment by kimyen2k** [comment]
Done 



![Image](https://user-images.githubusercontent.com/130328205/235099961-7c585907-d4b8-4bb4-8a3a-2949d0d398dd.png)



![Image](https://user-images.githubusercontent.com/130328205/235099964-e883a20f-77a7-4f5e-9873-84019eeb4159.png)
