### ISSUE TITLE
WFH Request > Spelling mistake: "Views Options"

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#82]
**Pre-Condition:**
User logins successfully and is on the W2 homepage

**Steps**

1. Click on "WFH Request" option at the sidebar
2. Click on "setting" icon next to "New Task" button
3. Observe

**Expected Result**
Letter "s" should be removed => View Option

**Actual Result**
Spelling mistake: "Views Options"

![Image](https://user-images.githubusercontent.com/127380920/231373967-9d7cf81d-18b2-42ca-a38b-c578f7ff261a.png)

**Comment by trucnguyen31** [comment]
Note: this issue also happens on Change office & Device Request task page

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/231637515-44a61f3c-e8c5-43c3-a664-da6f17cbc62f.png)
