### ISSUE TITLE
Remove all underscores at task progress column titles

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#83]
**Description:**

All off the underscores at task progress column titles should be removed and replaced by the spaces

**Screenshot**

![Image](https://user-images.githubusercontent.com/127380920/231376148-cfaf5877-8ae8-4179-927d-d48b61bf3fe5.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/231684899-c746b762-9dae-4475-9584-5b9cd5af7dd3.png)



![Image](https://user-images.githubusercontent.com/130328205/231684940-12ae39a5-e88e-4ecd-ab7a-3182a0b53b23.png)




![Image](https://user-images.githubusercontent.com/130328205/231684832-15c03d99-f720-4eb8-9d42-90316d3c4871.png)
