### ISSUE TITLE
Change Office Request > Some titles at task progress columns aren't suitable

### ISSUE THREAD

**Issue by trucnguyen31** [nccasia/w2-ui#84]
**Pre-condition:**
User logins successfully and is on the W2 homepage 

**Steps**

1. Click on the "Change Office Request" option at the sidebar
2. Observe the task progress columns

**Expected Result**

- "Wait PM Approval" should be changed to "PM Approval"
- "Destination Office Approval" should be changed to "New Office Approval"

**Actual Result**
Some titles at task progress columns aren't suitable

![Image](https://user-images.githubusercontent.com/127380920/231378563-96757d34-7e8f-4518-887d-8279632a522f.png)

**Comment by kimyen2k** [comment]
Done 


![Image](https://user-images.githubusercontent.com/130328205/231685355-d2ff0f06-3df1-4ce1-96a6-5965092bbb77.png)
